name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [main, alpha, beta]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  autofix:
    name: autofix
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup Tools
        uses: tanstack/config/.github/setup@e4b48f16568324f76f467aa4c2aac2f05db632c3 # main
      - name: Fix formatting
        run: pnpm format
      - name: Apply fixes
        uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
        with:
          commit-message: 'ci: apply automated fixes'
